<h1 align="center"><b>Modelación Financiera I</b></h1>
<h1 align="center"><b> Módulo 4, parte 1 </b></h1>
<h1 align="center"><b> Manipulación de datos y visualización  </b></h1>

*** 

***Docente:*** Santiago Rúa Pérez, PhD.

***e-mail:*** srua@udemedellin.edu.co

***Herramienta:*** [Jupyter Notebook](http://jupyter.org/)

***Kernel:*** Python 3.7

***MEDELLÍN - COLOMBIA***

***2022***

***

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item">
    <li><span><a href="#Introducci%C3%B3n-a-pandas" data-toc-modified-id="Introducci%C3%B3n-a-pandas-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introducción a pandas</a></span></li> 
    <li><span><a href="#Indexaci%C3%B3n-y-selecci%C3%B3n" data-toc-modified-id="Indexaci%C3%B3n-y-selecci%C3%B3n-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Indexación y selección</a></span></li>   
    <li><span><a href="#Operaciones-y-manejo-de-datos-faltantes" data-toc-modified-id="Operaciones-y-manejo-de-datos-faltantes-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operaciones y manejo de datos faltantes</a></span></li> 
    <li><span><a href="#Combinaci%C3%B3n-de-conjunto-de-datos" data-toc-modified-id="Combinaci%C3%B3n-de-conjunto-de-datos-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Combinación de conjunto de datos</a></span></li> 
    <li><span><a href="#Agregaciones-y-agrupaciones" data-toc-modified-id="Agregaciones-y-agrupaciones-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Agregaciones y agrupaciones</a></span></li> 
    <li><span><a href="#Apuntes-finales" data-toc-modified-id="Apuntes-finales-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Apuntes finales</a></span></li> 
    </ul></div>

## Introducción a pandas

Pandas es una libreria de python construida con base en `numpy` el cual maneja una implementación eficiente de datos utilizando una estructura conocida como `DataFrame`. Este objeto es un arreglo multidimensional con etiquetas para las filas y columnas, y a menudo con datos heterogéneos o datos faltantes. en forma sencilla, un `DataFrame` puede ser visto como un arreglo de `numpy` con nombre a las filas y columnas

### Pandas Series

Un objeto tipo Pandas `Series`, es un arreglo unidimensional con datos indexados, puede ser creado desde una lista asi:

In [2]:
import numpy as np
import pandas as pd

data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

La salida del objeto tiene tanto los valores como indices para los mismos, los cuales pueden accederse utilizando los atributos `values` e `index`. Los `values` son un simple arreglo de `numpy`, mientras que los indices son un objeto tipo `pd.Index`

In [4]:
print(data.values)
print(type(data.values))

[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>


In [7]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)


Como ocurre con los arreglo de `numpy`, las series de pandas pueden accederse utilizando notación `[]`, asi

In [9]:
print(data[2])
print(data[:3])

0.75
0    0.25
1    0.50
2    0.75
dtype: float64


Parece entonces que las series de pandas, son simplemente un arreglo de `numpy`, sin embargo, estos presentan funcionalidades extendidas. Por ejemplo, podemos indicar el indice a cada una de las filas de la serie

In [11]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['c']

0.75

Inclusive se puede utilizar indices no contiguos

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

Adicionalmente, la serie de pandas puede verse como un diccionario especializado. Notese que en el ejemplo anterior se accede como si fuera un diccionario. Lo anterior posibilita construir una serie de pandas con base en un diccionario como se muestra a continuación

In [16]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Sin embargo, a diferencia de un diccionario común, el acceso a los datos puede ser del estilo slicing, como:

In [19]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Pandas DataFrame

Una vez discutido la series de pandas, se puede entender el objeto tipo `DataFrame`. En este caso, la analogía de esta estructura es como un arreglo de dos dimensiones con indices y columnas flexibles. Por ejemplo, nosotros podemos construir una `DataFrame` con base en dos `Series`:

In [20]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [22]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Primero notese que ya aparece una tabla el Dataframe, con etiqueta en las columnas y filas. Adicionalmente, la creación del `DataFrame` se da a través de un diccionario. A diferencia de la serie, este objeto nuevo tiene columnas tambien

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

Para acceder a la información del `DataFrame` se puede realizar utilizando las etiquetas de las columnas e indices. Primero se debe hacer la indexación de la columna y luego la fila. 

In [27]:
states['area']['California']

423967

Para la creacción de `DataFrame` se puede utilizar las siguientes herramientas:

- De un objeto tipo Serie
- De una lista de diccionario
- De un diccionario de objetos tipo serie
- De una arreglo multidimensional

In [29]:
print(population)
pd.DataFrame(population, columns=['population'])

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [31]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [32]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [35]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.774895  0.257992
b  0.155071  0.970640
c  0.196813  0.725840

### Objeto tipo Pandas Index

Hemos observado que tanto los objetos tipo `Series` y `DataFrame` contienen explicitamente un objeto tipo `index`. Este objeto puede ser visto como un arreglo inmutable o como un cojunto ordenado. Por ejemplo 

In [36]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [37]:
print(ind[1])
print(ind[::2])
print(ind.size, ind.shape, ind.ndim, ind.dtype)

3
Int64Index([2, 5, 11], dtype='int64')
5 (5,) 1 int64


A diferencia de un arreglo, estos indices son inmutables, por lo que el código a continuación genera un error
``` python
ind[1] = 0

``` 

Como conjuntos ordenados, se pueden realizar operaciones de intersección, unión, o diferencia simétrica

In [38]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
print(indA & indB)
print(indA | indB)
print(indA ^ indB)

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Int64Index([1, 2, 9, 11], dtype='int64')


## Indexación y selección

La selección e indexación posibilita tomar partes de las series o dataframe para realizar algun tipo de procesamiento con estos.

### Selección en Series

Vimos que las Series pueden ser tratadas como un diccionario teniendo en cuenta que la llave esta dada por el nombre del índice. Adicionalmente, se vio que a diferencia de un diccionario, tambien tiene las características de un arreglo de numpy, por lo que se pueden realizar slicing en los mismos

In [39]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [40]:
data['b']

0.5

In [41]:
'a' in data

True

In [42]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [44]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [45]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [47]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [48]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Otra forma de acceder a la información dentro de una serie de pandas, es utilizando los atributos `loc` e `iloc`. Lo anterior se realiza con el objetivo de no generar confusiones cuandos los indices de las series son números. Por ejemplo

In [49]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [50]:
# explicit index when indexing
data[1]

'a'

In [52]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Para evitar estas confusiones, pandas brinda atributos a las series y dataframe para exponer parte del objeto. No se considera métodos, pero si atributos propios del objeto. Cuando utilizamos `loc` hacemos referencia al indice explicito de la serie

In [54]:
data.loc[1]

'a'

In [56]:
data.loc[1:3]

1    a
3    b
dtype: object

Por otro lado `iloc` hace refencia a la indexación implicita, como si se trabajara con un arreglo de numpy

In [57]:
data.iloc[1]

'b'

In [58]:
data.iloc[1:3]

3    b
5    c
dtype: object

Finalmente `ix` se analizará en el contexto de los dataframes

### Selección en DataFrames

Recuerde que los DataFrames funcionan como arreglos de dos dimensiones, por lo que se deberá tener en cuenta la información tanto de la fila como de la columna. Una forma de analizarlos, es viendolos como una lista de diccionarios que comparten el mismo indice. Teniendo esto presente una forma de acceder es

In [3]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [4]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [5]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [6]:
data.area is data['area']

True

In [8]:
data.pop is data['pop']

False

En el ejemplo anterior, `pop()` es un método del objeto, por lo que puede entrar en conflicto con el nombre de la columna. Por lo anterior se debe trata de evitar de asignar valores utilizando la notación de atributos. Estaría mal decir
``` python
data.pop = z
```
deberia ser 
```python
data['pop'] = z
```

Se puede agregar nuevas columnas, mediante operaciones u otros elementos

In [9]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

***DataFrame como arreglo de dos dimensiones ...***

Se puede acceder directamente a los valores de la matriz, realizar transpuesta, utilizar `iloc`, entre otras opciones

In [10]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [11]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [12]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [14]:
data.values[0,:]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [16]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [17]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [19]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [20]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## Operaciones y manejo de datos faltantes

Uno de los elementos esenciales de `numpy` es la velocidad de ejecución cuando se trata de operaciones matemáticas sobre este tipo de arreglos. Pandas hereda muchas de estas funcionalidades con una pequeña mejora: cuando se aplican operaciones unitarias o funciones trigonométricas, el resultado preservará el indice de la fila y columna. Analizemos como trabaja esto para un objeto de Pandas

In [22]:
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
print(ser)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
print(df)

0    6
1    3
2    7
3    4
dtype: int32
   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4


In [23]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [24]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

Notese que en los ejemplos anterior el indice se preservar y se hace un broadcasting sobre todos los elementos del objeto de la ufunc aplicada. Ahora, si se realiza operaciones unitarias, pandas alinea dichas operaciones cuando es posible

In [25]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

Para aquellas ciudades que un dato es faltantes, el resultado será `NaN`. Las demas operaciones las alinea por índice. Miremos otros ejemplos

In [26]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

Si el resultado que se quiere sea diferente para cuando no se de la alineacion, entonces se puede utilizar el método correspondiente

In [27]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [30]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
print(A)

B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
print(B)

A + B

   A   B
0  1  11
1  5   1
   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6


A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [40]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Datos faltantes en Pandas

En las aplicaciones reales, raramente los datos esta homogenos o limpios. Particularmente, muchos conjuntos de datos tienen una cantidad grande de datos faltantes. Para tratar los datos faltantes en los DataFrame se pueden utilizar dos formas: usando una máscara la cual indica de forma global donde estan los valores faltantes, o elegir un valor sentinela el cual nos indicará si ese dato es faltante.

Lo que se refiere a la libreria de Pandas, este problema lo resuelve utilizando sentinelas: utilizar el valor especial `NaN`, y el obejto `None`. 

***``None``*** ***: Pythonic***

Utilizando este como sentinela, lo que se crea es un objeto que me representa el dato faltante. Como es un objeto de python, no se puede usar de forma arbitraria para hacer operaciones amtemáticas. 

In [41]:
import numpy as np
import pandas as pd
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

Si se trata de obtener una agregación, entonces se obtendrá un error

```python
vals1.sum()
```

***``NaN``*** ***: Manejando datos faltantes numéricos***

Esta forma de representar datos faltantes, y especificamente numéricos, es reconocida por diferentes estandares. Lo que posibilita realizar operaciones

In [42]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [43]:
1 + np.nan 

nan

In [44]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

Si se quiere hacer agregaciones que ignoren estos valores, entonces

In [46]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

En el caso de la libreria de Pandas, automáticamente se hace un casting a NaN. 

|Typeclass     | Conversion When Storing NAs | NA Sentinel Value      |
|--------------|-----------------------------|------------------------|
| ``floating`` | No change                   | ``np.nan``             |
| ``object``   | No change                   | ``None`` or ``np.nan`` |
| ``integer``  | Cast to ``float64``         | ``np.nan``             |
| ``boolean``  | Cast to ``object``          | ``None`` or ``np.nan`` |

### Operaciones con valores nulos

Como vimos, Pandas trata de igual forma `None` que `NaN` para indicar valores faltantes

Para facilitar esta convención, hay varios métodos que ayuda a trabajar con esto:


- `isnull()`: genera una máscara booleana para indicar los valores faltantes
- `notnull()`: lo opuesto a `isnull()`
- `dropna()`: retorna una versión filtrada de los datos
- `fillna()`: retorna una copia de los datos con los valores faltantes llenados

In [47]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [49]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [50]:
data.dropna()

0        1
2    hello
dtype: object

In [51]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [52]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [53]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [55]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [56]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [57]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [58]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

## Combinación de conjunto de datos

Uno de los estudios mas interesantes viene de combinar diferentes estudios de diferentes fuentes de datos. Estas operaciones pueden consistir en concatenar dos conjuntos de datos o realizar uniones mas complejas. Pandas incluye dentro de su libreria, métodos que facilitan estas uniones de diferentes fuentes de datos.

In [67]:
import pandas as pd
import numpy as np

def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)
    
# example DataFrame
make_df('ABC', range(3))


A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

Al igual que `np.concat` para la libreria de `numpy`, pandas tiene un método para realizar las concatenaciones. Recordemos como funciona para numpy

In [62]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

En el caso de pandas, `pd.concat` tiene funciones similares a las de numpy, pero opciones adicionales como parámetros para la concatenación

```python
# Signature in Pandas v0.18
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)
```


In [64]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [66]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [75]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
pd.concat([df3, df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

***Duplicación de indices***

Una diferencia importante entre la concatenación de numpy y pandas, es que pandas preserva el indice cuando los hace, lo que puede ocasiona duplicidad en los indices

In [78]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index  # make duplicate indices!
df = pd.concat([x, y])
df

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

Para evitar este tipo de problemas, lo que se puede hacer es hacer una verificación de integralidad de los indices, por ejemplo

In [84]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


Como solución se puede indicar que ignore los indices

In [85]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

***Concatenación con uniones***

En los ejemplos vistos, solo se hacen concatenaciones de conjuntos de datos que tienen las mismas columnas. Pero que pasa si este no es el caso?. Considere el caso donde se comparten información en algunas columnas y otras no. Por defecto los datos no disponibles seran llenados con NaN. Para cambiar este comportamiento, uno puede especificar diferentes parámetros en la concatenación

In [89]:
df5 = make_df('ABC', [1, 2])
print(df5)
df6 = make_df('BCD', [3, 4])
print(df6)

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4


In [90]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

Si se requieren hacer la concatenación teniendo en cuenta la intereseccion de los conjuntos, entonces

In [91]:
pd.concat([df5, df6], join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

La union siempre está activada por defecto y corresponde al parámetro `outer`

In [96]:
pd.concat([df5, df6], join='outer')

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

***Concatenación utlizando merge***

A diferencia de la concatenación, `merge` nos sirve para realizar uniones basadas en álgebra relacional, el cual es usado típicamente en bases de datos. La fortaleza del álgebra relacional es que permite la construcción de diferentes bloques para realizar las uniones de acuerdo a nuestras necesidades. Estas uniones que se logran con merge pueden dividirse en tres categorias:

- Uno-a-uno (one-to-one): consiste en hacer concatenación columna a columna
- Muchos-a-uno (many-to-one): en este caso dos columnas tienen entradas duplicadas
- Muchos-a-muchos (many-to-many):

In [100]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


*como seria one-to-one*

In [99]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

*como seria many-to-one*

In [102]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [103]:
pd.merge(df3, df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

*como seria many-to-many*

In [105]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [106]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

## Agregaciones y agrupaciones

## Apuntes finales